In [26]:
import pandas as pd
import numpy as np
import os
import sys
from colorama import Fore, Back, Style
from datetime import datetime, timedelta
pd.set_option('display.max_columns', None)

In [27]:
ASSEST_SB =  pd.read_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\INPUT FOLDER\ASSET_INITIATION_INVENTORY_SB.csv")
ASSEST_NB = pd.read_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\INPUT FOLDER\ASSET_INITIATION_INVENTORY_NB.csv")
INFRA_SB = pd.read_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\INPUT FOLDER\Infrastructure_Devices_SB.csv",sep=';')
INFRA_NB = pd.read_csv( r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\INPUT FOLDER\Infrastructure_Devices_NB.csv",sep=';')
METER_STATUS_NB = pd.read_csv( r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\INPUT FOLDER\METER_STATUS_NB.csv")
METER_STATUS_SB = pd.read_csv( r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\INPUT FOLDER\METER_STATUS_SB.csv")

In [28]:
ASSEST_NB = ASSEST_NB.astype(str)
ASSEST_NB.columns = ASSEST_NB.columns.str.upper()
ASSEST_NB = ASSEST_NB.apply(lambda x: x.str.strip() if x.dtype == 'O' else x)
ASSEST_NB.columns = ASSEST_NB.columns.str.strip()



ASSEST_SB = ASSEST_SB.astype(str)
ASSEST_SB.columns = ASSEST_SB.columns.str.upper()
ASSEST_SB = ASSEST_SB.apply(lambda x: x.str.strip() if x.dtype == 'O' else x)
ASSEST_SB.columns = ASSEST_SB.columns.str.strip()
#-------------------------------------------------------------------------------------------

In [29]:
ASSEST_NB.head(1)

,METERNUMBER,MFG_SERIAL_NUM,UDC_ID,NETWORK_ID,INSTALLATIONNUMBER,STATUS,INSERT_TIME,"DECODE(D.ORG_ID,52,'SBPDCL',102,'NBPDCL')"
0,GOEGP4968974,GP4968974,404759210464692,2001:4490:0800:6073:0000:0000:0000:0001,MUZW-2290805636,Retired,9/2/2019 1:07:37 AM,NBPDCL

In [30]:
# rename the column name

ASSEST_NB.rename(
    columns = {"METERNUMBER":"METERNUMBER_NB","MFG_SERIAL_NUM": "MFG_SERIAL_NUM_NB",
    "UDC_ID":"UDC_ID_NB","NETWORK_ID":"NETWORK_ID_NB",
    "INSTALLATIONNUMBER":"INSTALLATIONNUMBER_NB","STATUS":"STATUS_NB","INSERT_TIME":"INSERT_TIME_NB",
    "DECODE(D.ORG_ID,52,'SBPDCL',102,'NBPDCL')":"UTILITY_NB"},inplace=True
)



#-----------------------------------------------------------------




ASSEST_SB.rename(
    columns = {"METERNUMBER":"METERNUMBER_SB","MFG_SERIAL_NUM": "MFG_SERIAL_NUM_SB",
    "UDC_ID":"UDC_ID_SB","NETWORK_ID":"NETWORK_ID_SB",
    "INSTALLATIONNUMBER":"INSTALLATIONNUMBER_SB","STATUS":"STATUS_SB","INSERT_TIME":"INSERT_TIME_SB",
    "DECODE(D.ORG_ID,52,'SBPDCL',102,'NBPDCL')":"UTILITY_SB"},inplace=True
)

In [31]:
ASSEST_SB.head(1)

,METERNUMBER_SB,MFG_SERIAL_NUM_SB,UDC_ID_SB,NETWORK_ID_SB,INSTALLATIONNUMBER_SB,STATUS_SB,INSERT_TIME_SB,UTILITY_SB
0,GOEGP4970294,GP4970294,404759210464358,2001:4490:0800:5F25:0000:0000:0000:0001,nan,Meter Shop,8/7/2019 1:26:44 PM,SBPDCL

In [32]:
ASSEST_NB['METERNUMBER_NB'] = ASSEST_NB['METERNUMBER_NB'].apply(lambda x: x.strip())
ASSEST_NB['MFG_SERIAL_NUM_NB'] = ASSEST_NB['MFG_SERIAL_NUM_NB'].apply(lambda x: x.strip())
ASSEST_NB['UDC_ID_NB'] = ASSEST_NB['UDC_ID_NB'].apply(lambda x: x.strip())
ASSEST_NB['NETWORK_ID_NB'] = ASSEST_NB['NETWORK_ID_NB'].apply(lambda x: x.strip())
ASSEST_NB['INSTALLATIONNUMBER_NB'] = ASSEST_NB['INSTALLATIONNUMBER_NB'].apply(lambda x: x.strip())
ASSEST_NB['STATUS_NB'] = ASSEST_NB['STATUS_NB'].apply(lambda x: x.strip())
ASSEST_NB['INSERT_TIME_NB'] = ASSEST_NB['INSERT_TIME_NB'].apply(lambda x: x.strip())
ASSEST_NB['UTILITY_NB'] = ASSEST_NB['UTILITY_NB'].apply(lambda x: x.strip())
#ASSEST_NB['METERNUMBER_NB'] = ASSEST_NB['METERNUMBER_NB'].apply(lambda x: x.strip())

print("assest Nb is done")



#  assest sb data 



ASSEST_SB['METERNUMBER_SB'] = ASSEST_SB['METERNUMBER_SB'].apply(lambda x: x.strip())
ASSEST_SB['MFG_SERIAL_NUM_SB'] = ASSEST_SB['MFG_SERIAL_NUM_SB'].apply(lambda x: x.strip())
ASSEST_SB['UDC_ID_SB'] = ASSEST_SB['UDC_ID_SB'].apply(lambda x: x.strip())
ASSEST_SB['NETWORK_ID_SB'] = ASSEST_SB['NETWORK_ID_SB'].apply(lambda x: x.strip())
ASSEST_SB['INSTALLATIONNUMBER_SB'] = ASSEST_SB['INSTALLATIONNUMBER_SB'].apply(lambda x: x.strip())
ASSEST_SB['STATUS_SB'] = ASSEST_SB['STATUS_SB'].apply(lambda x: x.strip())
ASSEST_SB['INSERT_TIME_SB'] = ASSEST_SB['INSERT_TIME_SB'].apply(lambda x: x.strip())
ASSEST_SB['UTILITY_SB'] = ASSEST_SB['UTILITY_SB'].apply(lambda x: x.strip())


print("assest Sb is done")

assest Nb is done
assest Sb is done

In [33]:
ASSEST_NB.head()

,METERNUMBER_NB,MFG_SERIAL_NUM_NB,UDC_ID_NB,NETWORK_ID_NB,INSTALLATIONNUMBER_NB,STATUS_NB,INSERT_TIME_NB,UTILITY_NB
0,GOEGP4968974,GP4968974,404759210464692,2001:4490:0800:6073:0000:0000:0000:0001,MUZW-2290805636,Retired,9/2/2019 1:07:37 AM,NBPDCL
1,GOEGP4881969,GP4881969,404751250450510,2001:4490:0800:A41A:0000:0000:0000:0001,DALGND-816,Installed,9/9/2019 1:01:27 AM,NBPDCL
2,GOEGP4881776,GP4881776,404751250009815,fd00:0000:0800:E2CF:0000:0000:0000:0001,BRUBR-7529,Installed,9/9/2019 1:01:28 AM,NBPDCL
3,GOEGP4967107,GP4967107,404751250461212,2001:4490:0800:C6D4:0000:0000:0000:0001,DALGND-833,Installed,9/9/2019 1:01:29 AM,NBPDCL
4,GOEGP4880200,GP4880200,404751250470195,2001:4490:0800:CAA6:0000:0000:0000:0001,nan,Meter Shop,9/9/2019 1:01:30 AM,NBPDCL

#### METERNUMBER_NB  &  MFG_SERIAL_NUM_NB  : -   is not same
#### METERNUMBER_SB  &  MFG_SERIAL_NUM_SB  : -   is not same

In [34]:
ASSEST_NB[ASSEST_NB['METERNUMBER_NB'].str[3:]!=ASSEST_NB['MFG_SERIAL_NUM_NB']]

,METERNUMBER_NB,MFG_SERIAL_NUM_NB,UDC_ID_NB,NETWORK_ID_NB,INSTALLATIONNUMBER_NB,STATUS_NB,INSERT_TIME_NB,UTILITY_NB
27996,GOEGP7505514,GP7430333,404751250624075,2001:4490:0800:34D3:0000:0000:0000:0001,52222024950,Installed,3/25/2021 1:02:46 AM,NBPDCL
76617,﻿GOEGP4875734,GP4875734,nan,nan,nan,Meter Shop,11/24/2019 1:05:13 AM,NBPDCL
94382,LNTLTLT0690717,LT0690717,405856706692242,2405:0203:0525:FA4D:0000:0000:0000:0010,nan,Meter Shop,11/8/2023 10:39:54 AM,NBPDCL
145855,LNTLTLT0085831,LT0085831,nan,nan,nan,Meter Shop,11/8/2023 10:39:54 AM,NBPDCL
181331,GOEGP7501388,GP7430334,404751250624074,2001:4490:0800:34D2:0000:0000:0000:0001,52102833493,Installed,3/25/2021 1:02:46 AM,NBPDCL
196639,LNTLTLT0129262,LT0129262,nan,nan,nan,Meter Shop,11/8/2023 10:39:54 AM,NBPDCL
204346,﻿GOEGP1025800,GP1025800,nan,nan,nan,Meter Shop,11/9/2019 1:07:40 AM,NBPDCL
204406,GOEGP5968449,nan,nan,nan,nan,Installed,12/4/2019 10:55:08 AM,NBPDCL
220919,LNTLTLT0174521,LT0174521,405856706113267,2405:0203:0521:DF14:0000:0000:0000:0010,nan,Meter Shop,12/16/2023 8:02:31 PM,NBPDCL
273879,LNTLTLT0143605,LT0143605,nan,nan,nan,Meter Shop,11/8/2023 10:39:54 AM,NBPDCL
329648,LNTLTLT0160195,LT0160195,405856706310683,2405:0203:0522:662C:0000:0000:0000:0010,nan,Meter Shop,12/4/2023 10:13:24 PM,NBPDCL
332042,﻿GOEGP4876920,GP4876920,nan,nan,nan,Meter Shop,11/24/2019 1:05:35 AM,NBPDCL
375502,LNTLTLT0171228,LT0171228,nan,nan,nan,Meter Shop,11/8/2023 10:39:54 AM,NBPDCL
502865,LNTLTLT0109546,LT0109546,nan,nan,nan,Meter Shop,11/8/2023 10:39:54 AM,NBPDCL
579088,LNTLTLT0166555,LT0166555,nan,nan,nan,Meter Shop,11/8/2023 10:39:54 AM,NBPDCL
584437,LNTLTLT0201982,LT0201982,nan,nan,nan,Meter Shop,12/4/2023 10:13:24 PM,NBPDCL
584438,LNTLTLT0298457,LT0298457,nan,nan,nan,Meter Shop,12/4/2023 10:13:24 PM,NBPDCL
630088,LNTLTLT0168391,LT0168391,nan,nan,nan,Meter Shop,11/8/2023 10:39:54 AM,NBPDCL
630090,LNTLTLT0181976,LT0181976,nan,nan,nan,Meter Shop,11/8/2023 10:39:54 AM,NBPDCL
712058,LNTLTLT0081077,LT0081077,405856706169885,2405:0203:0520:77DA:0000:0000:0000:0010,nan,Meter Shop,12/4/2023 10:13:24 PM,NBPDCL
714490,﻿GOEGP4875733,GP4875733,nan,nan,nan,Meter Shop,11/12/2019 1:07:36 AM,NBPDCL
768027,GOEGP7501267,GP7430332,404751250624071,2001:4490:0800:34D0:0000:0000:0000:0001,5002554290,Retired,3/25/2021 1:02:46 AM,NBPDCL
808471,LNTLTLT0373192,LT0373192,nan,nan,nan,Meter Shop,11/8/2023 10:39:54 AM,NBPDCL
808649,LNTLTLT0529625,LT0529625,405856707266486,2405:0203:052B:D76B:0000:0000:0000:0010,nan,Meter Shop,11/8/2023 10:39:54 AM,NBPDCL
808651,LNTLTLT0152310,LT0152310,nan,nan,nan,Meter Shop,11/8/2023 10:39:54 AM,NBPDCL
813931,LNTLTLT0131193,LT0131193,405856706076967,2405:0203:0522:C94C:0000:0000:0000:0010,nan,Meter Shop,12/4/2023 10:13:24 PM,NBPDCL

In [35]:
ASSEST_NB.shape

(816257, 8)

In [36]:

# Custom function to update meter numbers
def update_meter_number(meter_number):
    if meter_number.startswith('GP') or meter_number.startswith('GL'):
        return 'GOE' + meter_number
    elif meter_number.startswith('LT'):
        return 'LNT' + meter_number
    else:
        return meter_number

# Apply the custom function to each element in the 'METER NO.' column
ASSEST_NB['METER_NO_NB'] = ASSEST_NB['MFG_SERIAL_NUM_NB'].apply(update_meter_number)
ASSEST_SB['METER_NO_SB'] = ASSEST_SB['MFG_SERIAL_NUM_SB'].apply(update_meter_number)

# DATA DUPLICACY IN NB

In [37]:
# duplicacy on METER NO


ASSEST_NB_METER_NO_DUPLICATED = ASSEST_NB[ASSEST_NB.duplicated(subset=['MFG_SERIAL_NUM_NB'],keep=False)].sort_values(by=['MFG_SERIAL_NUM_NB'],ascending=True)
ASSEST_NB_METER_NO_DUPLICATED.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\OUTPUT FOLDER MDM\ASSEST_NB_METER_NO_DUPLICATED.csv")


# duplicacy on IP

ASSEST_NB_IP_DUPLICATED = ASSEST_NB[(ASSEST_NB.duplicated(subset=['NETWORK_ID_NB'],keep=False)) & (ASSEST_NB['NETWORK_ID_NB']!='nan')].sort_values(by='NETWORK_ID_NB',ascending=True)
ASSEST_NB_IP_DUPLICATED.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\OUTPUT FOLDER MDM\ASSEST_NB_IP_DUPLICATED.csv")

# DUPLICACY ON INSTALLATION NO

ASSEST_NB_INSTALLATION_DUPLICATED = ASSEST_NB[(ASSEST_NB.duplicated(subset=['INSTALLATIONNUMBER_NB'],keep=False)) & (ASSEST_NB['INSTALLATIONNUMBER_NB']!='nan')].sort_values(by=['INSTALLATIONNUMBER_NB'],ascending=False)
ASSEST_NB_INSTALLATION_DUPLICATED.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\OUTPUT FOLDER MDM\ASSEST_NB_INSTALLATION_DUPLICATED.csv")

,METERNUMBER_NB,MFG_SERIAL_NUM_NB,UDC_ID_NB,NETWORK_ID_NB,INSTALLATIONNUMBER_NB,STATUS_NB,INSERT_TIME_NB,UTILITY_NB,METER_NO_NB
516802,GOEGL8548353,GL8548353,405856706536765,2405:0203:0528:DC24:0000:0000:0000:0010,5004017369,Installed,1/5/2024 12:08:17 PM,NBPDCL,GOEGL8548353
101977,GOEGL8548353,GL8548353,405856706536765,2405:0203:0528:DC24:0000:0000:0000:0010,5003906341,Installed,1/5/2024 12:08:17 PM,NBPDCL,GOEGL8548353
750486,GOEGL8548408,GL8548408,405856706891833,2405:0203:0528:DC5B:0000:0000:0000:0010,5002031916,Meter Shop,1/15/2024 4:25:22 PM,NBPDCL,GOEGL8548408
317246,GOEGL8548408,GL8548408,405856706891833,2405:0203:0528:DC5B:0000:0000:0000:0010,nan,Meter Shop,1/15/2024 4:25:22 PM,NBPDCL,GOEGL8548408
355146,GOEGL8548429,GL8548429,405856706891688,2405:0203:0528:DC70:0000:0000:0000:0010,5003933058,Installed,1/4/2024 12:58:17 PM,NBPDCL,GOEGL8548429
...,...,...,...,...,...,...,...,...,...
500498,LNTLT8040763,LT8040763,405856707400178,2405:0203:052F:9258:0000:0000:0000:0010,5002587518,Refurbished,10/19/2022 1:05:34 AM,NBPDCL,LNTLT8040763
551354,LNTLT8040846,LT8040846,405856707400059,2405:0203:052F:92AB:0000:0000:0000:0010,5000377189,Refurbished,10/19/2022 1:05:34 AM,NBPDCL,LNTLT8040846
168885,LNTLT8040846,LT8040846,405856706772112,2405:0203:0527:80E0:0000:0000:0000:0010,5000377189,Refurbished,10/19/2022 1:05:34 AM,NBPDCL,LNTLT8040846
550493,LNTLT8041357,LT8041357,405856706905617,2405:0203:0527:8AA6:0000:0000:0000:0010,5003809376,Refurbished,10/19/2022 1:05:34 AM,NBPDCL,LNTLT8041357
677841,LNTLT8041357,LT8041357,405856707402921,2405:0203:052F:94AA:0000:0000:0000:0010,5003809376,Refurbished,10/19/2022 1:05:34 AM,NBPDCL,LNTLT8041357

# DATA DUPLICACY IN SB

In [39]:
# duplicacy on METER NO


ASSEST_SB_METER_NO_DUPLICATED = ASSEST_SB[ASSEST_SB.duplicated(subset=['MFG_SERIAL_NUM_SB'],keep=False)].sort_values(by=['MFG_SERIAL_NUM_SB'],ascending=True)
ASSEST_SB_METER_NO_DUPLICATED.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\OUTPUT FOLDER MDM\ASSEST_SB_METER_NO_DUPLICATED.csv")

# duplicacy on IP

ASSEST_SB_IP_DUPLICATED = ASSEST_SB[(ASSEST_SB.duplicated(subset=['NETWORK_ID_SB'],keep=False)) & (ASSEST_SB['NETWORK_ID_SB']!='nan')].sort_values(by='NETWORK_ID_SB',ascending=True)
ASSEST_SB_IP_DUPLICATED.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\OUTPUT FOLDER MDM\ASSEST_SB_IP_DUPLICATED.csv")


# DUPLICACY ON INSTALLATION NO

ASSEST_SB_INSTALLATION_DUPLICATED = ASSEST_SB[(ASSEST_SB.duplicated(subset=['INSTALLATIONNUMBER_SB'],keep=False)) & (ASSEST_SB['INSTALLATIONNUMBER_SB']!='nan')].sort_values(by=['INSTALLATIONNUMBER_SB'],ascending=False)
ASSEST_SB_INSTALLATION_DUPLICATED.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\OUTPUT FOLDER MDM\ASSEST_SB_INSTALLATION_DUPLICATED.csv")

In [44]:
ASSEST_SB_METER_NO_DUPLICATED.head()

,METERNUMBER_SB,MFG_SERIAL_NUM_SB,UDC_ID_SB,NETWORK_ID_SB,INSTALLATIONNUMBER_SB,STATUS_SB,INSERT_TIME_SB,UTILITY_SB,METER_NO_SB
513915,GOEGL8548300,GL8548300,405856707172350,2405:0203:0532:43AE:0000:0000:0000:0010,5001970345,Refurbished,5/4/2022 1:04:08 PM,SBPDCL,GOEGL8548300
248749,GOEGL8548300,GL8548300,405856706536659,2405:0203:0528:DBEF:0000:0000:0000:0010,5001970345,Refurbished,5/4/2022 1:04:08 PM,SBPDCL,GOEGL8548300
477210,GOEGL8548303,GL8548303,405856706536685,2405:0203:0528:DBF2:0000:0000:0000:0010,5004056701,Installed,5/4/2022 1:04:08 PM,SBPDCL,GOEGL8548303
974015,GOEGL8548303,GL8548303,405856707299383,2405:0203:0531:9328:0000:0000:0000:0010,5004056701,Installed,5/4/2022 1:04:08 PM,SBPDCL,GOEGL8548303
544052,GOEGL8548303,GL8548303,405856706536685,2405:0203:0528:DBF2:0000:0000:0000:0010,5002973847,Installed,5/4/2022 1:04:08 PM,SBPDCL,GOEGL8548303

In [40]:
ASSEST_NB.head(1)

,METERNUMBER_NB,MFG_SERIAL_NUM_NB,UDC_ID_NB,NETWORK_ID_NB,INSTALLATIONNUMBER_NB,STATUS_NB,INSERT_TIME_NB,UTILITY_NB,METER_NO_NB
0,GOEGP4968974,GP4968974,404759210464692,2001:4490:0800:6073:0000:0000:0000:0001,MUZW-2290805636,Retired,9/2/2019 1:07:37 AM,NBPDCL,GOEGP4968974

In [41]:
ASSEST_SB.head(1)

,METERNUMBER_SB,MFG_SERIAL_NUM_SB,UDC_ID_SB,NETWORK_ID_SB,INSTALLATIONNUMBER_SB,STATUS_SB,INSERT_TIME_SB,UTILITY_SB,METER_NO_SB
0,GOEGP4970294,GP4970294,404759210464358,2001:4490:0800:5F25:0000:0000:0000:0001,nan,Meter Shop,8/7/2019 1:26:44 PM,SBPDCL,GOEGP4970294

In [42]:
CZXVBGF FD

SyntaxError: invalid syntax (3023882178.py, line 1)

# merge nb and sb file

In [ ]:



# JOIN ON   METER NO.

MDM_NB_SB_DATA_METER_NO = pd.merge(ASSEST_NB, ASSEST_SB, left_on=['METERNUMBER_NB'], right_on=['METERNUMBER_SB'], how='inner')
MDM_NB_SB_DATA_METER_NO.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\OUTPUT FOLDER HES\MDM_NB_SB_DATA_METER_NO.csv")


# join on 

MDM_NB_SB_DATA_SERIAL_NO = pd.merge(ASSEST_NB, ASSEST_SB, left_on=['MFG_SERIAL_NUM_NB'], right_on=['MFG_SERIAL_NUM_SB'], how='inner')
MDM_NB_SB_DATA_SERIAL_NO.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\OUTPUT FOLDER HES\MDM_NB_SB_DATA_SERIAL_NO.csv")


# JOIN ON INSTALLATION FILE

HES_NB_SB_DATA_INSTALLATION_NO = pd.merge(INFRA_NB_COMM_DATA, INFRA_SB_COMM_DATA, left_on=['UTILITYSITEID_NB'], right_on=['UTILITYSITEID_SB'], how='inner')
HES_NB_SB_DATA_INSTALLATION_NO.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\OUTPUT FOLDER HES\HES_NB_SB_DATA_INSTALLATION_NO.csv")


# JOIN ON IP DATA

MDM_NB_SB_DATA_IP = pd.merge(ASSEST_NB, ASSEST_SB, left_on=['NETWORK_ID_NB'], right_on=['NETWORK_ID_NB'], how='inner')
MDM_NB_SB_DATA_IP=HES_NB_SB_DATA_IP[(HES_NB_SB_DATA_IP['IP_NB']==HES_NB_SB_DATA_IP['IP_SB']) & (HES_NB_SB_DATA_IP['IP_NB']!='nan')  &  (HES_NB_SB_DATA_IP['IP_SB']!='nan') ]
MDM_NB_SB_DATA_IP.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\OUTPUT FOLDER HES\MDM_NB_SB_DATA_IP.csv")


# JOIN ON METER AND INSTALLATION DATA

HES_NB_SB_DATA_METER_AND_IP = pd.merge(INFRA_NB_COMM_DATA, INFRA_SB_COMM_DATA, left_on=['UTILITYDEVICEID_NB','IP_NB'], right_on=['UTILITYDEVICEID_SB','IP_SB'], how='inner')
HES_NB_SB_DATA_METER_AND_IP.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\hes_mdm\OUTPUT FOLDER HES\HES_NB_SB_DATA_METER_AND_IP.csv")

In [ ]:
from colorama import Fore, Back, Style

# Print highlighted text
print(Fore.RED + 'This text is red')
print(Back.GREEN + 'This text has a green background')
print(Style.BRIGHT + 'This text is bright')

# Reset colors
print(Style.RESET_ALL + 'Back to normal')

This text is red
This text has a green background
This text is bright
Back to normal